### ISSUE TITLE
Issues with the code under the "Usage" part

### ISSUE THREAD

**Issue by juliagorman** [talmolab/sleap-anipose#25]
I tried to run the command in step 2 of the "usage" section. 

`slap-draw_board --board_name my/path/board.jpg --board_X 8 --board_Y 11 --square_length 24.0 --marker_length 18.75 --marker_bits 4 --dict_size 1000 --image_width 1440 --image_height 1440 --save my/path/board.toml`

There were several issues. First --board_X needs to be board_x as well as board_Y needs to be board_y. --image_with needs to be img_width and image height needs to be img_height. Once I replaced my/path/board.jpg and .toml with "path/board.jpg" and "path/board.toml", I received the following error: 'TypeError: draw_board_cli() got an unexpected keyword argument 'board_name' I also tried removing the quotes and got this error. 

So then, I went into the calibration.py python file and found the keyword argument in draw_board_cli(), which in place of board_name seemed to be save_file. Replacing this seemed to have solved this error, but a new error occurred:

`TypeError: Expected Ptr<cv::aruco::Dictionary> for argument 'dictionary'`

And this one i dont know how to solve

**Comment by sean-afshar** [comment]
Hi @juliagorman, 

Thanks for pointing out these issues with SLEAP-Anipose. We have recently pushed a series of new updates to streamline the CLI functions and have not updated the guides accordingly. 

As for the type error bug you are encountering, this is due to needing to input the actual aruco dictionary object to the cv2 command that draws boards. There have recently been updates to opencv-contrib-python that have made certain parts of our code inoperable, and this is one of them. To fix this, we have to use `aruco.getPredefinedDictionary(aruco.ARUCO_DICT_4X4_1000)` as our aruco dictionary input.


I will update the draw_board function to reflect this change and will be updating the guides as well. Version 0.1.0 will contain these overhauls and be released shortly. 

If you have any more issues, please ask. Greatly appreciate the feedback.

**Comment by sean-afshar** [comment]
Hi @juliagorman,

Our new release of v0.1.1 just came out with the relevant fixes. I was able to run the draw_board sample code in the usage guide successfully. I am going to close this issue, but if any bugs persist, please let us know.  

Best,
Sean Afshar

**Comment by juliagorman** [comment]
thank you i was able to successfully run that command
