### ISSUE TITLE
reprojection error histogram indicates great calibration, reprojection error images say otherwise (#41?)

### ISSUE THREAD

**Issue by delaroob** [talmolab/sleap-anipose#57]
Hi!

I think the issue in https://github.com/talmolab/sleap-anipose/issues/41 may still persist? At least I pip installed the new sleap-anipose with the fix by @ericleonardis , that has already been merged, and the same thing is happening (see photos attached of an average reprojection error image and the histogram). I also tried downloading it manually, and I got the same results.
![Image](https://github.com/user-attachments/assets/4334ce73-2270-4b11-b3ad-8b0dcfdd453a)
![Image](https://github.com/user-attachments/assets/d2891aa7-486c-4e75-ac83-d594777fd1aa)

I thought that maybe only the images are incorrect again, and it didn't affect calibration, but when running triangulation for a **multianimal** project, I already get these warnings, not sure if it's relevant:
```
slap-triangulate --p2d C:/mentes/multikazmer_sleap/to3d/20241029/0002 --calib C:/mentes/multikazmer_sleap/to3d/20241029/0002/calibration.toml --fname C:/mentes/multikazmer_sleap/to3d/20241029/0002/points3d.h5
C:\mentes\anaconda\envs\sleap-anipose\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\mentes\anaconda\envs\sleap-anipose\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
C:\mentes\anaconda\envs\sleap-anipose\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\mentes\anaconda\envs\sleap-anipose\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
```
Anyway, the points3d.h5 file _is_ created, but when visualizing it (in R), the data is pretty bad.

I'm not sure what else it can be, if not the calibration: it can't really be the 2D tracking accuracy because I was able to calibrate -> triangulate the same 2D SLEAP data with other codes.

Let me know if I sould provide any other info, and thanks in advance for any help!

**Comment by ericleonardis** [comment]
Sorry to hear you are still having trouble with calibration. I am not convinced this is related to issue #41. I started a fresh environment, pip installed, and did not replicate any errors regarding reprojection images. 

From the looks of it, your reprojection error histogram does not indicate a good calibration. I also do not think that your reprojection images show anything which contradicts the histogram. From the looks of the histogram, your calibration is not working well. It could be worse, but I would say that your calibration is failing for other reasons. The image shows errors within the ranges described by your histogram. 

Are you still using two cameras? As I've said in the past, two cameras are not going to yield good calibration results. This is not a system intended for stereo calibration with two cameras. I do not recommend using two cameras for multi-camera 3D triangulation. Adding more cameras will be critical. 

There appear to be some issues with the detections outright. Many do seem to be correct though. Your image looks blurry and low quality. This may lead to bad detections. This is different from the other video you send me in the past which was higher quality. Having bad detections will lead to bad 3D models. In addition, the 3D model is bad because you need more information from other camera viewpoints to reduce ambiguity.  The addition of more camera views and higher quality images will reduce these problems with accuracy. 

Those warnings are not relevant and should not effect anything as far as I know. 

To give you a point of reference, here is what a good calibration would look like using 4 cameras. The y-axis values are very different from your histogram. You can see even from this high quality image many detections are still missing, but the reprojections match indicating a good calibration.  These images were generated from my fresh pip installed environment.

![Image](https://github.com/user-attachments/assets/1b619465-979a-4aee-8bd4-b60d3b4196a8)
![Image](https://github.com/user-attachments/assets/792223b3-d300-4f23-8aac-82ca72875ee5)

Hope we can figure out a solution to improve your calibration results by improving the calibration videos themselves.

**Comment by delaroob** [comment]
Oh, now i see that i have completely misinterpreted the histogram, my mistake:)

And thank you for your quick reply and for fixing the issue itself!
